version: '3'

services:
    nginx:
        image: nginx
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
            - ./nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        networks:
            - nginx_network
        depends_on:
            - web
    certbot:
        image: certbot/certbot
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    web:
        build: 
            context: ./api
        volumes:
            - ./api:/app
        depends_on:
            - db
        links:
            - db
        networks:
            - db_network
            - nginx_network
        command: gunicorn -b 0.0.0.0:80 server:app --capture-output
    db:
        image: mongo:4.1
        environment:
            MONGO_INITDB_DATABASE: expo-production
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:21017
        command: --quiet  
        networks:
            - db_network
networks:
    nginx_network:
        driver: bridge
    db_network:
        driver: bridge
